version: '3.9'
services:
  users:
    container_name: users
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8080'
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: users-pg
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: users_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    
